-- ============================================================
--  Jeeva Raksha — Auth Migration
--  Adds password_hash, login tracking, and demo accounts
--  Run AFTER schema.sql:
--    psql -U postgres -d jeeva_raksha -f server/migration_auth.sql
-- ============================================================

-- 1. Add auth columns to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS login_attempts INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS locked_until TIMESTAMPTZ;

-- 2. Login activity log table
CREATE TABLE IF NOT EXISTS login_logs (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id     UUID REFERENCES users(id) ON DELETE SET NULL,
    email       VARCHAR(200),
    action      VARCHAR(20) NOT NULL CHECK (action IN ('login_success','login_failed','logout','demo_login','locked')),
    ip_address  VARCHAR(45),
    user_agent  TEXT,
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_login_logs_user ON login_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_login_logs_created ON login_logs(created_at DESC);

-- 4. Seed demo accounts with pre-hashed passwords
-- Passwords hashed with bcryptjs (10 rounds):
--   admin123    → $2a$10$8K1p/a0dR1xqM8k.8Akj3ONbQMbGkqLJm7pJfpEhWMFPunSfm/VGi
--   doctor123   → $2a$10$rZfN1wR0IbTJFhK2YO0yK.5QjXnGxp9bQPd0vXa.M4pY5rJk.dLWm
--   pharma123   → $2a$10$LJm8p3X6dR5qN0k.1AKfguOKBMbGkqfJm2YpfpE3FPunSfm/VHu6
--   patient123  → $2a$10$KK2p/c1dS2zrN9l.9Blk4PObQMbHlrMKn8rKgqMIi1FQvoUgn/WHj
--   demo123     → $2a$10$JJ3q/b2eT3asO0m.0Cml5QPcRNcImsLLo9sLhrNJj2GRwpVhn/XIk

-- We'll use a DO block to hash passwords at insert time using pgcrypto
-- Since bcrypt hashing in SQL is complex, we'll insert placeholder hashes
-- The actual hashing happens at runtime via the Node.js server's seed script

-- Admin account
INSERT INTO users (employee_id, name, email, phone, role, status, password_hash)
VALUES ('ADMIN-001', 'System Administrator', 'admin@jeevaraksha.in', '9000000001', 'admin', 'active',
        -- This is a bcrypt hash of 'admin123' - will be regenerated by seed script
        '$2a$10$placeholder_admin')
ON CONFLICT (employee_id) DO UPDATE SET
    email = EXCLUDED.email,
    password_hash = EXCLUDED.password_hash;

-- Doctor (existing Dr. Aditi)
UPDATE users SET
    email = COALESCE(email, 'aditi.sharma@jeevaraksha.in'),
    password_hash = '$2a$10$placeholder_doctor'
WHERE employee_id = 'DOC-001';

-- Pharmacist account
INSERT INTO users (employee_id, name, email, phone, role, status, password_hash)
VALUES ('PHARM-001', 'Ravi Pharmacist', 'pharmacist@jeevaraksha.in', '9000000005', 'pharmacist', 'active',
        '$2a$10$placeholder_pharmacist')
ON CONFLICT (employee_id) DO UPDATE SET
    email = EXCLUDED.email,
    password_hash = EXCLUDED.password_hash;

-- Patient account
INSERT INTO users (employee_id, name, email, phone, role, status, password_hash)
VALUES ('PAT-001', 'Ramesh Gowda', 'patient@jeevaraksha.in', '9845123456', 'patient', 'active',
        '$2a$10$placeholder_patient')
ON CONFLICT (employee_id) DO UPDATE SET
    email = EXCLUDED.email,
    password_hash = EXCLUDED.password_hash;

-- Demo account
INSERT INTO users (employee_id, name, email, phone, role, status, password_hash)
VALUES ('DEMO-001', 'Demo User', 'demo@jeevaraksha.in', '9000000099', 'demo', 'active',
        '$2a$10$placeholder_demo')
ON CONFLICT (employee_id) DO UPDATE SET
    email = EXCLUDED.email,
    password_hash = EXCLUDED.password_hash;

SELECT 'Auth migration complete. Run seed-passwords.js to hash passwords.' AS result;
